### ISSUE TITLE
some errors after deployed to heroku

### ISSUE THREAD

**Issue by kakamband** [marceloglacial/2020-brinca-wordpress#3]
Hi Marcelo,
After deployed to heroku give error below on admin panel notice :
`Deprecated: contextual_help is deprecated since version 3.3.0! Use get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab() instead. in /app/web/wp/wp-includes/functions.php on line 5234`
& WP_SITEURL=${WP_HOME}/wp is a wrong env for heroku path , i delete it , DB_HOST is comment by # instead of it's requirement 
& can't browse website homepage , always automatic redirect to login page 
& my important question is how to install plugins/themes without push from local host ?
waiting for your repsonse
finest regards

**Comment by marceloglacial** [comment]
@kakamband Hi! I noticed the same warning message but I usually ignored it heheh

Regarding the website redirect, this repo was created to a specific project that uses a headless front-end based on React.

If you want disable the redirect plugin, you can remove this line on composer file: https://github.com/marceloglacial/2020-brinca-wordpress/blob/9005a897e4b8af6b9d77df58887433036db97ba7/composer.json#L50

To install, update, add and/or remove plugins, you have to edit the composer file. When you update/push your master branch, Heroku will build the app with the changes.

I hope it helps.

P.S.: When I finished this project I'm going to create a new boilerplate repo for Wordpress on Heroku :)
